/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as LoginMagicLinkErrorRouteImport } from './routes/login.magic-link.error'
import { Route as LoginMagicLinkTokenRouteImport } from './routes/login.magic-link.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginMagicLinkErrorRoute = LoginMagicLinkErrorRouteImport.update({
  id: '/login/magic-link/error',
  path: '/login/magic-link/error',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginMagicLinkTokenRoute = LoginMagicLinkTokenRouteImport.update({
  id: '/login/magic-link/$token',
  path: '/login/magic-link/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/login/magic-link/$token': typeof LoginMagicLinkTokenRoute
  '/login/magic-link/error': typeof LoginMagicLinkErrorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/login/magic-link/$token': typeof LoginMagicLinkTokenRoute
  '/login/magic-link/error': typeof LoginMagicLinkErrorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/login/magic-link/$token': typeof LoginMagicLinkTokenRoute
  '/login/magic-link/error': typeof LoginMagicLinkErrorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/tanstack-query'
    | '/login/magic-link/$token'
    | '/login/magic-link/error'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/tanstack-query'
    | '/login/magic-link/$token'
    | '/login/magic-link/error'
  id:
    | '__root__'
    | '/'
    | '/demo/tanstack-query'
    | '/login/magic-link/$token'
    | '/login/magic-link/error'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  LoginMagicLinkTokenRoute: typeof LoginMagicLinkTokenRoute
  LoginMagicLinkErrorRoute: typeof LoginMagicLinkErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/magic-link/error': {
      id: '/login/magic-link/error'
      path: '/login/magic-link/error'
      fullPath: '/login/magic-link/error'
      preLoaderRoute: typeof LoginMagicLinkErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/magic-link/$token': {
      id: '/login/magic-link/$token'
      path: '/login/magic-link/$token'
      fullPath: '/login/magic-link/$token'
      preLoaderRoute: typeof LoginMagicLinkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  LoginMagicLinkTokenRoute: LoginMagicLinkTokenRoute,
  LoginMagicLinkErrorRoute: LoginMagicLinkErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
