name: build-app-image

on:
  push:
    paths:
      - ".github/workflows/build-app-image.yml"
      - "homecooking-app/**"
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Log in to container registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Setup docker buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Build and push the docker image"
        uses: docker/build-push-action@v6
        with:
          push: true
          context: homecooking-bot/
          tags: ghcr.io/jirkavrba/homecooking/app:latest
